name: New Release
on:
  push:
    tags:
      - "v*"
  release:
    types: [published]
    branches: [main]

jobs:
  publish:
    name: Publish on PyPI
    runs-on: ubuntu-latest
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Set up the environment
        uses: ./.github/actions/setup-poetry-env

      - name: Export tag
        id: vars
        run: echo tag=${GITHUB_REF#refs/*/} >> $GITHUB_OUTPUT

      - name: Build source files
        run: |
          source .venv/bin/activate
          poetry version $RELEASE_VERSION
          poetry build
        env:
          RELEASE_VERSION: ${{ steps.vars.outputs.tag }}

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}